-- Supabase setup for automatic profile rows and favorites integrity
-- Run this in the Supabase SQL Editor.

begin;

create table if not exists public.profiles (
  id uuid not null references auth.users on delete cascade,
  username text,
  avatar_url text,
  bio text,
  primary key (id)
);

create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users on delete cascade,
  cave_name text not null,
  created_at timestamptz default now()
);

create table if not exists public.activity_feed (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users on delete cascade,
  user_name text,
  cave_name text not null,
  message text not null,
  created_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);

alter table public.activity_feed
  add column if not exists user_name text;

alter table public.profiles enable row level security;
alter table public.favorites enable row level security;
alter table public.activity_feed enable row level security;

alter table public.favorites
  drop constraint if exists favorites_user_cave_unique;

alter table public.favorites
  add constraint favorites_user_cave_unique unique (user_id, cave_name);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, username, avatar_url, bio)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', new.email),
    null,
    null
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

insert into public.profiles (id, username, avatar_url, bio)
select
  au.id,
  coalesce(au.raw_user_meta_data->>'full_name', au.email),
  null,
  null
from auth.users au
where not exists (
  select 1
  from public.profiles p
  where p.id = au.id
);

drop policy if exists "User lesen eigenes Profil" on public.profiles;
drop policy if exists "User bearbeiten eigenes Profil" on public.profiles;
drop policy if exists "User sehen eigene Favoriten" on public.favorites;
drop policy if exists "User fügen Favoriten hinzu" on public.favorites;
drop policy if exists "User löschen eigene Favoriten" on public.favorites;

create policy "User lesen eigenes Profil"
  on public.profiles
  for select
  using (auth.uid() = id);

create policy "User bearbeiten eigenes Profil"
  on public.profiles
  for update
  using (auth.uid() = id);

create policy "User sehen eigene Favoriten"
  on public.favorites
  for select
  using (auth.uid() = user_id);

create policy "User fügen Favoriten hinzu"
  on public.favorites
  for insert
  with check (auth.uid() = user_id);

create policy "User löschen eigene Favoriten"
  on public.favorites
  for delete
  using (auth.uid() = user_id);

drop policy if exists "Angemeldete sehen Feed" on public.activity_feed;
drop policy if exists "User schreiben Feed" on public.activity_feed;
drop policy if exists "Angemeldete leeren Feed" on public.activity_feed;

create policy "Angemeldete sehen Feed"
  on public.activity_feed
  for select
  using (auth.role() = 'authenticated');

create policy "User schreiben Feed"
  on public.activity_feed
  for insert
  with check (auth.uid() = user_id);

create policy "Angemeldete leeren Feed"
  on public.activity_feed
  for delete
  using (auth.role() = 'authenticated');

create index if not exists activity_feed_created_at_idx
  on public.activity_feed (created_at desc);

create index if not exists activity_feed_user_id_idx
  on public.activity_feed (user_id);

create or replace function public.handle_favorite_activity()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_name text;
begin
  select coalesce(p.username, u.raw_user_meta_data->>'full_name', u.email, 'Jemand')
    into actor_name
  from auth.users u
  left join public.profiles p on p.id = u.id
  where u.id = new.user_id;

  insert into public.activity_feed (user_id, user_name, cave_name, message, metadata)
  values (
    new.user_id,
    actor_name,
    new.cave_name,
    actor_name || ' hat Höhle ' || new.cave_name || ' entdeckt',
    jsonb_build_object('favorite_id', new.id)
  );

  return new;
end;
$$;

drop trigger if exists on_favorite_created on public.favorites;

create trigger on_favorite_created
after insert on public.favorites
for each row execute function public.handle_favorite_activity();

commit;
